version: '3.9'
# Defining the compose version

services:
  # Nginx server
  nginx:
    # Build context
    build: ./nginx
    # Mapping machine and container ports
    ports:
      - 1337:80
    # Storage volumes
    volumes:
      - ./nginx:/home/app/Gunicorn_nginx_Docker_and_Django_Storage/nginx/
      - static_volume:/home/app/Gunicorn_nginx_Docker_and_Django/static_volume
      - media_volume:/home/app/Gunicorn_nginx_Docker_and_Django/media_volume
    depends_on:
      - web
    restart: "on-failure"

  # Django application
  web:
    # Build context
    build: .
    # Build commands
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --no-input &&
                    gunicorn config.wsgi:application --bind 0.0.0.0:8000  --reload"   
    # Storage volumes
    volumes:
      - .:/home/app/Gunicorn_nginx_Docker_and_Django/
    # Exposing port 8000
    expose: 
    - 8000
    restart: "on-failure"

volumes:
  # concept of names volumes
  static_volume:
  media_volume:


