version: '3.9'
# Defining the compose version

services:
  # Nginx server
  nginx:
    # Build context
    build: ./nginx
    container_name: nginx_web_container
    # Mapping machine and container ports
    ports:
      - 1337:80
    # Storage volumes
    volumes:
      - media-data:/media
      - static-data:/static
    depends_on:
      - web1
      - web2
      - web3
    restart: "always"

  # Django application
  web1:
    # Build context
    build: .
    container_name: django_web_container1
    # Build commands
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --no-input &&
                    gunicorn config.wsgi:application --bind 0.0.0.0:8000  --reload" 
    # command:  gunicorn config.wsgi:application --bind 0.0.0.0:8000  --reload

    # Storage volumes
    volumes:
      - .:/src
      - media-data:/vol/media
      - static-data:/vol/static
    # Exposing port 8000
    expose: 
      - 8000
    restart: "always"
    depends_on:
      - postgres_db_container

  # Django application
  web2:
    # Build context
    build: .
    container_name: django_web_container2
    # Build commands
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --no-input &&
                    gunicorn config.wsgi:application --bind 0.0.0.0:8000  --reload" 
    # command:  gunicorn config.wsgi:application --bind 0.0.0.0:8000  --reload

    # Storage volumes
    volumes:
      - .:/src
      - media-data:/vol/media
      - static-data:/vol/static
    # Exposing port 8000
    expose: 
      - 8000
    restart: "always"
    depends_on:
      - postgres_db_container

  # Django application
  web3:
    # Build context
    build: .
    container_name: django_web_container3
    # Build commands
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --no-input &&
                    gunicorn config.wsgi:application --bind 0.0.0.0:8000  --reload" 
    # command:  gunicorn config.wsgi:application --bind 0.0.0.0:8000  --reload

    # Storage volumes
    volumes:
      - .:/src
      - media-data:/vol/media
      - static-data:/vol/static
    # Exposing port 8000
    expose: 
      - 8000
    restart: "always"
    depends_on:
      - postgres_db_container

  # Database (Postgres)
  postgres_db_container:
    image: postgres:12.4
    container_name: postgres_db_container
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ../local_data1/postgres:/var/lib/postgresql/data

volumes:
  # concept of names volumes
  media-data:
  static-data:


